### ISSUE TITLE
Reduce Codecov runs to only those that might affect coverage

### ISSUE THREAD

**Issue by jsync-swirlds** [hiero-ledger/hiero-block-node#917]
### Story Form

As a Block Node Engineer
I want to avoid unnecessary CI runs
So that I can focus on meaningful results

### Technical Notes

Currently the Codecov tools run for every miniscule change to a pull request, even just editing a title or adding a label. These changes cannot affect code coverage, and result in excess runs of the tool many times more than necessary, even running long after a PR is closed or merged.
We wish to reduce the tool triggers to only run on pull requests, and only when the files in the pull request have changed or the target branch has changed.

Here is a suggested modification to avoid constant or excessive runs.
```yaml
# Only comment on PRs initially and when coverage changes
comment:
  layout: "diff, flags, files"
  behavior: new # deletes old comment and posts a new one
  require_changes: true

coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 1%
        only_pulls: true
    project:
      default:
        target: 80%
        threshold: 1%
        branches:
          - main
```
